### ISSUE TITLE
Build chess board and chess logic

### ISSUE THREAD

**Issue by statebait** [Lyearn/szachy#1]
Use existing libraries to build a chess board with added chess logic.

Should be built via separate components.

Reference links:
https://chessboardjs.com/
https://github.com/oakmac/chessboardjs
https://github.com/justinfagnani/chessboard-element/
https://github.com/jhlywa/chess.js
https://codepen.io/pianotiles2/pen/bBBpgE](https://codepen.io/pianotiles2/pen/bBBpgE

**Comment by anup-a** [comment]
Hey .... looking forward to work on this.
Could you elaborate about what all logic should be included?

**Comment by statebait** [comment]
Regular chess logic - see https://github.com/jhlywa/chess.js

When a player is in the game he should able to select a piece and see all the valid moves etc.
