### ISSUE TITLE
Build a board management UI

### ISSUE THREAD

**Issue by statebait** [Lyearn/szachy#2]
The idea is to build a board management UI where one user (admin) can create several chess boards in which other users can play against each other or the admin user itself can play with himself.

Building this UI is agnostic of the chess board itself since building the chess board is a separate task. Also this UI will be agnostic of backend and how the users will actually connect to the platform. 

The focus here is on the layout, functionality and user friendliness.

Different scenarios to consider:
- Admin user should be able to create multiple boards
- Admin user should be able to decide who plays on each board
- All users can play against one or more games simultaneously
...etc

**Comment by manishdangi98** [comment]
Hey @statebait, I think React-admin can be a good option for this use case.

**Comment by statebait** [comment]
If you think so then you are free to go ahead and use it.
